channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - ivar
  - lofreq
  - pangolin
  - snakemake-minimal<=6.8.0
  - gofasta
  - ucsc-fatovcf>=426
  - usher>=0.3.2
  - pip=19.3.1
  - pip:
    - git+https://github.com/cov-lineages/pangolin-data.git
    - git+https://github.com/cov-lineages/scorpio.git
    - git+https://github.com/cov-lineages/constellations.git
